### ISSUE TITLE
.github/actionlint.yaml not work

### ISSUE THREAD

**Issue by jk2K** [arahatashun/vscode-actionlint#4]
refer to https://github.com/rhysd/actionlint/blob/main/docs/config.md

I want to add custom-label for my self-hosted runner

.github/actionlint.yaml
```yaml
self-hosted-runner:
  # Labels of self-hosted runner in array of string
  labels:
    - centos-7.7
```

but I got error

<img width="430" alt="image" src="https://user-images.githubusercontent.com/4025839/236486518-393b1f76-69cb-4631-9a54-743eb02dbdc6.png">

.github/workflows/1.yaml

```yaml
name: test1
on:
  workflow_dispatch:
    inputs:
      recordId:
        description: recordId
        default: "0"

jobs:
  job1:
    name: test
    runs-on: centos-7.7
    steps:
      - name: "step1"
        run: |
          echo "Hello World"
```
